#!/bin/bash
NAME="aaron8bit/devdocker"
VERSION="latest"
IMAGE="${NAME}:${VERSION}"

exec docker run -it \
 --hostname=DevDocker \
 --rm=true \
 --net=host \
 --workdir="$(pwd)" \
 --volume=/etc/localtime:/etc/localtime \
 --volume=/var/run/docker.sock:/var/run/docker.sock \
 --volume="${HOME}":"${HOME}" \
 --volume="${HOME}/.gitconfig":"/home/aja/.gitconfig" \
 --volume="${HOME}/.ssh":"/home/aja/.ssh" \
 --volume="${HOME}/repos":"/home/aja/repos" \
 --workdir="/home/aja/repos" \
 ${IMAGE} \
zsh 

